version: '3.1'
services:
    web:
        image: building
        command: ["npm", "run", "app"]
        build: .
        ports:
            - 6666:6666
        depends_on:
            - redis
            - postgres

    redis:
        image: redis:4.0.5-alpine
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis

    postgres:
        image: postgres:10
        restart: always
        volumes:
            - ./init-db.sql
        # ports:
        #     - "1112:1112"
        # environment:
        #     - POSTGRES_USER=postgres
        #     - POSTGRES_PASSWORD=987654321Qq
        #     - POSTGRES_DB=building
