version: '3.1'
services:
    web:
        image: building
        command: bash -c "npm run app"
        build: .
        ports:
            - 8000:8000
        depends_on:
            - redis
            - postgres

    redis:
        image: redis:4.0.5-alpine
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis

    postgres:
        image: postgres:10
        restart: always
        volumes:
            - ./init-db.sh
